//! The theory band (D-UI-17): what you are playing, drawn as geometry.
//!
//! Three pictures of the same twelve notes, any combination of which can be on
//! at once. They share one band above everything else and split its width.
//!
//!   * the **circle of fifths**, which arranges keys so that neighbours share
//!     six of seven notes — the reason a modulation to the next sector sounds
//!     like a step and one to the opposite sector sounds like a shove,
//!   * the **Tonnetz**, a lattice where the three axes are the fifth, the major
//!     third and the minor third, so every triad is a triangle and two chords
//!     that share two notes are two triangles that share an edge, and
//!   * the **harmonic triangles**, I-IV-V pointing up with i-iv-v inverted
//!     through the same centre, which is the tonic-subdominant-dominant
//!     relationship as one shape you can slide to a new key.
//!
//! Like `piano.rs` and `fretboard_panel.rs`, this module is dumb: it is handed
//! a set of sounding pitch classes and it draws. It does not detect anything.
//! What it adds over those two is that a pitch class here has no octave and no
//! string — the whole point of these diagrams is what survives forgetting both.

use crate::fonts;
use crate::settings::Settings;
use egui::{Align2, Color32, FontId, Painter, Pos2, Rect, Stroke, StrokeKind, Vec2};

/// Band height for a 1300pt-wide window. Large, because these are diagrams
/// rather than readouts: a circle of fifths with unreadable sector labels is
/// decoration. Scaled with everything else (spec §3.2).
pub const BAND_H_AT_1300: f64 = 300.0;

/// Height of the theory band for a window `w` points wide, or 0 when nothing
/// is selected. Truncated like every other band in the layout.
pub fn band_height(w: f32, views: Views) -> f32 {
    if views.count() == 0 {
        return 0.0;
    }
    (BAND_H_AT_1300 * w as f64 / 1300.0).trunc() as f32
}

// ── the twelve notes ───────────────────────────────────────────────────────

const SHARP_NAMES: [&str; 12] = [
    "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B",
];
const FLAT_NAMES: [&str; 12] = [
    "C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B",
];

fn pc_name(pc: u8, prefer_flats: bool) -> &'static str {
    let i = (pc % 12) as usize;
    if prefer_flats {
        FLAT_NAMES[i]
    } else {
        SHARP_NAMES[i]
    }
}

/// The twelve major keys in ascending fifths from C. Index is also the number
/// of sharps, up to the enharmonic seam at six.
const FIFTHS: [u8; 12] = [0, 7, 2, 9, 4, 11, 6, 1, 8, 3, 10, 5];

/// The key signature at position `i` around the circle, as (sharps, flats).
/// Exactly one of the two is non-zero except at C, which has neither, and at
/// the seam, which is six of either depending on how you spell it.
fn signature(i: usize) -> (u8, u8) {
    match i {
        0 => (0, 0),
        1..=6 => (i as u8, 0),
        _ => (0, (12 - i) as u8),
    }
}

/// The major scale on `root`, as a 12-bit pitch-class mask.
pub fn major_scale(root: u8) -> u16 {
    const STEPS: [u8; 7] = [0, 2, 4, 5, 7, 9, 11];
    STEPS
        .iter()
        .fold(0u16, |m, s| m | 1 << ((root as u16 + *s as u16) % 12))
}

/// A major triad as a pitch-class mask.
pub fn major_triad(root: u8) -> u16 {
    (1 << (root % 12)) | (1 << ((root + 4) % 12)) | (1 << ((root + 7) % 12))
}

/// A minor triad as a pitch-class mask.
pub fn minor_triad(root: u8) -> u16 {
    (1 << (root % 12)) | (1 << ((root + 3) % 12)) | (1 << ((root + 7) % 12))
}

fn has(mask: u16, pc: u8) -> bool {
    mask & (1 << (pc % 12)) != 0
}

/// Read the root and quality back off one of the app's own chord labels.
///
/// Deliberately narrow. These labels are generated by `ivory-core`, so the
/// leading note name is always one of the twelve spellings above, and a
/// lower-case `m` that is not the start of `maj` is always minor quality. It
/// returns None rather than guessing on anything else — a diagram that points
/// at the wrong tonic is worse than one that points nowhere, because there is
/// no way to tell from looking at it.
pub fn parse_label(label: &str) -> Option<(u8, bool)> {
    let b = label.as_bytes();
    let letter = *b.first()?;
    let base = match letter {
        b'C' => 0,
        b'D' => 2,
        b'E' => 4,
        b'F' => 5,
        b'G' => 7,
        b'A' => 9,
        b'B' => 11,
        _ => return None,
    };
    let (root, rest) = match b.get(1) {
        Some(b'#') => ((base + 1) % 12, &label[2..]),
        Some(b'b') => ((base + 11) % 12, &label[2..]),
        _ => (base, &label[1..]),
    };
    // "m" is minor; "maj" is not, and neither is the "m" inside "dim".
    let minor = rest.starts_with('m') && !rest.starts_with("maj");
    Some((root, minor))
}

// ── what is selected ───────────────────────────────────────────────────────

/// Which diagrams are showing. Any combination, including none.
///
/// Three independent flags rather than one enum: the request was explicitly to
/// be able to see more than one at a time, and an enum would have to grow a
/// variant per combination to say that.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub struct Views {
    pub circle: bool,
    pub tonnetz: bool,
    pub triangles: bool,
}

impl Views {
    pub fn count(self) -> usize {
        self.circle as usize + self.tonnetz as usize + self.triangles as usize
    }

    pub fn any(self) -> bool {
        self.count() > 0
    }
}

/// One diagram, for the menu and for cycling.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum View {
    Circle,
    Tonnetz,
    Triangles,
}

impl View {
    pub const ALL: [View; 3] = [View::Circle, View::Tonnetz, View::Triangles];

    pub fn label(self) -> &'static str {
        match self {
            View::Circle => "Circle of Fifths",
            View::Tonnetz => "Tonnetz",
            View::Triangles => "Harmonic Triangles",
        }
    }

    pub fn is_on(self, v: Views) -> bool {
        match self {
            View::Circle => v.circle,
            View::Tonnetz => v.tonnetz,
            View::Triangles => v.triangles,
        }
    }
}

/// What the diagrams are drawing.
#[derive(Clone, Copy, Default, Debug)]
pub struct Input {
    /// Sounding pitch classes, bit `i` for pitch class `i`. Octaves are gone
    /// by design: none of these diagrams has an axis for them.
    pub pcs: u16,
    /// Lowest sounding pitch class. The fallback tonic when the detector has
    /// no name for what is being played, because a bass note is a better guess
    /// than C.
    pub bass: Option<u8>,
    /// Root and quality from the detected chord label, when there is one.
    pub root: Option<u8>,
    pub minor: bool,
}

impl Input {
    /// The tonic the key-centred diagrams orient themselves around: the
    /// detected root, else the bass, else C so the picture is still drawn.
    pub fn tonic(&self) -> u8 {
        self.root.or(self.bass).unwrap_or(0)
    }

    pub fn contains(&self, mask: u16) -> bool {
        self.pcs != 0 && (self.pcs & mask) == mask
    }
}

// ── palette ────────────────────────────────────────────────────────────────

struct Palette {
    bg: Color32,
    ink: Color32,
    faint: Color32,
    line: Color32,
    lit: Color32,
    lit_text: Color32,
    root: Color32,
}

fn palette(s: &Settings) -> Palette {
    let lit = s.white_key_active_color.to_color32();
    if s.dark_mode {
        Palette {
            bg: Color32::from_rgb(0x0a, 0x0a, 0x0a),
            ink: Color32::from_rgb(0xE8, 0xDC, 0xC0),
            faint: Color32::from_rgb(0x55, 0x50, 0x46),
            line: Color32::from_rgb(0x33, 0x30, 0x2a),
            lit,
            lit_text: Color32::BLACK,
            root: s.sustain_color.to_color32(),
        }
    } else {
        Palette {
            bg: Color32::from_rgb(0xE8, 0xDC, 0xC0),
            ink: Color32::from_rgb(0x1a, 0x1a, 0x1a),
            faint: Color32::from_rgb(0xa8, 0x9e, 0x88),
            line: Color32::from_rgb(0xc8, 0xbd, 0xa4),
            lit,
            lit_text: Color32::WHITE,
            root: s.sustain_color.to_color32(),
        }
    }
}

fn font(size: f32) -> FontId {
    FontId::new(size, fonts::courier_bold())
}

fn font_light(size: f32) -> FontId {
    FontId::new(size, fonts::courier())
}

// ── the band ───────────────────────────────────────────────────────────────

/// Divide `rect` into one cell per selected view, left to right in a fixed
/// order so turning one off never reshuffles the others.
pub fn cells(rect: Rect, views: Views) -> Vec<(View, Rect)> {
    let on: Vec<View> = View::ALL.into_iter().filter(|v| v.is_on(views)).collect();
    if on.is_empty() {
        return Vec::new();
    }
    let w = rect.width() / on.len() as f32;
    on.into_iter()
        .enumerate()
        .map(|(i, v)| {
            (
                v,
                Rect::from_min_size(
                    Pos2::new(rect.min.x + w * i as f32, rect.min.y),
                    Vec2::new(w, rect.height()),
                ),
            )
        })
        .collect()
}

pub fn draw(painter: &Painter, rect: Rect, views: Views, input: Input, s: &Settings) {
    let p = palette(s);
    painter.rect_filled(rect, 0.0, p.bg);

    let cells = cells(rect, views);
    for (i, (view, cell)) in cells.iter().enumerate() {
        // A hairline between panes, so three diagrams read as three and not as
        // one crowded one. Not drawn on the first, which has the band edge.
        if i > 0 {
            painter.line_segment(
                [
                    Pos2::new(cell.min.x, cell.min.y + 6.0),
                    Pos2::new(cell.min.x, cell.max.y - 6.0),
                ],
                Stroke::new(1.0_f32, p.line),
            );
        }
        let inner = cell.shrink(8.0);
        match view {
            View::Circle => draw_circle(painter, inner, input, &p, s),
            View::Tonnetz => draw_tonnetz(painter, inner, input, &p, s),
            View::Triangles => draw_triangles(painter, inner, input, &p, s),
        }
    }

    // Bottom edge, the same idea as the fretboard's top edge: the bands are
    // one window and need a seam or they read as one tall picture.
    painter.line_segment(
        [
            Pos2::new(rect.min.x, rect.max.y - 0.5),
            Pos2::new(rect.max.x, rect.max.y - 0.5),
        ],
        Stroke::new(1.0_f32, p.line),
    );
}

/// A title over each pane, in the space the diagrams leave for it.
fn title(painter: &Painter, rect: Rect, text: &str, p: &Palette) -> Rect {
    let h = (rect.height() * 0.09).clamp(9.0, 15.0);
    painter.text(
        Pos2::new(rect.center().x, rect.min.y + h * 0.5),
        Align2::CENTER_CENTER,
        text,
        font(h * 0.92),
        p.faint,
    );
    Rect::from_min_max(Pos2::new(rect.min.x, rect.min.y + h + 2.0), rect.max)
}

// ── circle of fifths ───────────────────────────────────────────────────────

/// Angle of circle position `i`, with C at twelve o'clock and fifths
/// clockwise. Screen y grows downward, so this is the usual convention with
/// the sign of the sine left alone.
fn circle_angle(i: usize) -> f32 {
    -std::f32::consts::FRAC_PI_2 + i as f32 * std::f32::consts::TAU / 12.0
}

fn draw_circle(painter: &Painter, rect: Rect, input: Input, p: &Palette, s: &Settings) {
    let rect = title(painter, rect, "CIRCLE OF FIFTHS", p);
    let c = rect.center();
    let r = rect.width().min(rect.height()) * 0.5 - 2.0;
    if r < 20.0 {
        return;
    }

    // Four bands: signature, major, minor, and a hub for the reading.
    let r_sig = r;
    let r_maj = r * 0.80;
    let r_min = r * 0.56;
    let r_hub = r * 0.34;

    let step = std::f32::consts::TAU / 12.0;
    for (i, &pc) in FIFTHS.iter().enumerate() {
        let a = circle_angle(i);
        let dir = Vec2::new(a.cos(), a.sin());

        // How well this key explains what is being played. All of it in the
        // scale is the bright case; this is the "closely related keys" the
        // circle exists to show, and it is why neighbours light together.
        let scale = major_scale(pc);
        let held = input.pcs.count_ones();
        let inside = (input.pcs & scale).count_ones();
        let fit = if held == 0 {
            0.0
        } else {
            inside as f32 / held as f32
        };

        // The sector wedge, drawn as a filled polygon between two radii. egui
        // has no arc fill, so the arc is walked in small steps; eight is under
        // half a degree of error at this radius and costs nothing.
        if fit > 0.0 {
            let mut poly = Vec::with_capacity(18);
            let a0 = a - step * 0.5;
            for k in 0..=8 {
                let t = a0 + step * k as f32 / 8.0;
                poly.push(c + Vec2::new(t.cos(), t.sin()) * r_maj);
            }
            for k in (0..=8).rev() {
                let t = a0 + step * k as f32 / 8.0;
                poly.push(c + Vec2::new(t.cos(), t.sin()) * r_min);
            }
            // Only a full fit gets real colour. A partial fit is a wash, or
            // every sector lights for every chord and the diagram says nothing.
            let alpha = if fit >= 1.0 { 190 } else { (fit * 55.0) as u8 };
            painter.add(egui::Shape::convex_polygon(
                poly,
                p.lit.gamma_multiply(alpha as f32 / 255.0),
                Stroke::NONE,
            ));
        }

        // Spokes.
        let a0 = a - step * 0.5;
        painter.line_segment(
            [
                c + Vec2::new(a0.cos(), a0.sin()) * r_min,
                c + Vec2::new(a0.cos(), a0.sin()) * r_sig,
            ],
            Stroke::new(1.0_f32, p.line),
        );

        let full = fit >= 1.0 && input.pcs != 0;
        let txt = if full { p.lit_text } else { p.ink };

        // Major key, outer.
        painter.text(
            c + dir * ((r_maj + r_min) * 0.5),
            Align2::CENTER_CENTER,
            pc_name(pc, s.prefer_flats),
            font(r * 0.135),
            txt,
        );

        // Relative minor, inner — a sixth above, which is the same key
        // signature and the reason it is drawn on the same spoke.
        //
        // Lower case rather than a trailing "m", which is how a circle of
        // fifths has always been labelled, and which also happens to be one
        // character narrower. Three characters of Courier does not fit in the
        // inner wedge: "Gbm" and "Dbm" crossed the ring they sit in.
        let rel = (pc + 9) % 12;
        painter.text(
            c + dir * ((r_min + r_hub) * 0.5),
            Align2::CENTER_CENTER,
            &pc_name(rel, s.prefer_flats).to_lowercase(),
            font_light(r * 0.105),
            p.ink.gamma_multiply(0.75),
        );

        // Key signature, outermost.
        let (sharps, flats) = signature(i);
        // ASCII accidentals, not U+266F/U+266D. Neither music glyph is in the
        // bundled faces or in the fallback chain, so both drew as tofu boxes;
        // and the app spells note names "Db" and "A#" everywhere else anyway,
        // so this is the consistent choice as well as the safe one.
        let sig = match (sharps, flats) {
            (0, 0) => String::new(),
            (n, 0) => format!("{n}#"),
            (0, n) => format!("{n}b"),
            _ => String::new(),
        };
        if !sig.is_empty() {
            painter.text(
                c + dir * ((r_sig + r_maj) * 0.5),
                Align2::CENTER_CENTER,
                &sig,
                font_light(r * 0.095),
                p.faint,
            );
        }

        // A pip on the rim for each sounding pitch class. This is the part
        // that shows the SHAPE of a voicing: a triad is three neighbours plus
        // one at four o'clock from them, a tritone is a diameter.
        if has(input.pcs, pc) {
            let is_root = input.root == Some(pc);
            painter.circle_filled(
                c + dir * (r_maj + (r_sig - r_maj) * 0.12),
                r * 0.045,
                if is_root { p.root } else { p.lit },
            );
        }
    }

    for ring in [r_sig, r_maj, r_min, r_hub] {
        painter.circle_stroke(c, ring, Stroke::new(1.0_f32, p.line));
    }

    // The hub says what the picture is of, so the diagram is readable without
    // the chord strip and stays readable when the chord strip is turned off.
    if input.pcs != 0 {
        let tonic = input.tonic();
        painter.text(
            Pos2::new(c.x, c.y - r_hub * 0.28),
            Align2::CENTER_CENTER,
            &format!(
                "{}{}",
                pc_name(tonic, s.prefer_flats),
                if input.minor { "m" } else { "" }
            ),
            font(r * 0.19),
            p.ink,
        );
        // How many keys contain everything being played. Zero is the useful
        // reading, not an error: it means the voicing is chromatic.
        let n = FIFTHS
            .iter()
            .filter(|&&pc| input.pcs & !major_scale(pc) == 0)
            .count();
        painter.text(
            Pos2::new(c.x, c.y + r_hub * 0.38),
            Align2::CENTER_CENTER,
            &match n {
                0 => "no key fits".to_owned(),
                1 => "1 key".to_owned(),
                n => format!("{n} keys"),
            },
            font_light(r * 0.085),
            p.faint,
        );
    }
}

// ── Tonnetz ────────────────────────────────────────────────────────────────

/// The pitch class at lattice position (u, v): `u` fifths and `v` major thirds
/// from the origin. This one line is the whole Tonnetz — every property of the
/// diagram falls out of it.
pub fn tonnetz_pc(u: i32, v: i32, origin: u8) -> u8 {
    (((7 * u + 4 * v) % 12 + 12) % 12 + origin as i32) as u8 % 12
}

/// Where the Tonnetz nodes go inside a pane.
///
/// Pulled out of the drawing so it can be tested. The lattice is unbounded by
/// nature and a pane is not; every mistake this diagram can make is a mistake
/// about that boundary, and none of them is visible in a passing paint test.
struct Lattice {
    a: f32,
    h: f32,
    node_r: f32,
    rows: i32,
    cols: i32,
    x0: f32,
    y0: f32,
}

impl Lattice {
    /// Five rows shows the vertical period — the lattice repeats every three
    /// major thirds — with a row of context above and below it.
    const ROWS: i32 = 5;

    fn fit(rect: Rect) -> Option<Self> {
        let rows = Self::ROWS;
        let vspan = (rows - 1) as f32 * 0.8660254 + 0.6; // + a node either end
                                                         // A band this small is not a diagram. Bailing here also keeps `a_h`
                                                         // away from zero, which is what made the column count divide into
                                                         // infinity and then overflow `i32` on the way back — found by the
                                                         // every-size test, at a 40pt-wide window nobody would open on purpose.
        if !(rect.width() >= 32.0 && rect.height() >= vspan * 16.0) {
            return None;
        }
        let a_h = rect.height() / vspan;
        // Columns are whatever the width affords at that spacing, never fewer
        // than five — below that the horizontal axis stops showing a run of
        // fifths — and never so many that the names stop being readable.
        let shear = (rows - 1) as f32 * 0.5;
        let cols = (((rect.width() / a_h) - shear - 0.6).floor() + 1.0).clamp(5.0, 13.0) as i32;
        let a_w = rect.width() / ((cols - 1) as f32 + shear + 0.6);
        let a = a_h.min(a_w);
        if a < 16.0 {
            return None;
        }
        let h = a * 0.8660254; // equilateral: a * sqrt(3)/2
                               // The lattice is a sheared rhombus, so its bounding box is wider than
                               // the node grid by the shear. Centre the BOX, not the grid, or it
                               // sits left.
        let w_used = (cols - 1) as f32 * a + shear * a;
        let h_used = (rows - 1) as f32 * h;
        Some(Self {
            a,
            h,
            node_r: a * 0.30,
            rows,
            cols,
            x0: rect.center().x - w_used * 0.5,
            y0: rect.center().y + h_used * 0.5,
        })
    }

    fn at(&self, u: i32, v: i32) -> Pos2 {
        Pos2::new(
            self.x0 + u as f32 * self.a + v as f32 * self.a * 0.5,
            self.y0 - v as f32 * self.h,
        )
    }

    /// Whether a node at (u, v) is drawn. Whole nodes only: one clipped in
    /// half by the pane edge is a note name that is not a note name — the
    /// first render of this showed an "Eb" cut down to "Kb".
    fn shows(&self, rect: Rect, u: i32, v: i32) -> bool {
        rect.contains_rect(Rect::from_center_size(
            self.at(u, v),
            Vec2::splat(self.node_r * 2.0),
        ))
    }
}

fn draw_tonnetz(painter: &Painter, rect: Rect, input: Input, p: &Palette, s: &Settings) {
    let rect = title(painter, rect, "TONNETZ", p);
    // Everything below stays inside the pane. The lattice is unbounded by
    // nature, so without this it happily draws over the neighbouring diagram.
    let painter = &painter.with_clip_rect(rect);

    let Some(l) = Lattice::fit(rect) else {
        return;
    };
    let (rows, cols, node_r) = (l.rows, l.cols, l.node_r);
    let origin = input.tonic();
    let at = |u: i32, v: i32| l.at(u, v);

    // Triads first, so the nodes sit on top of their triangles.
    //
    // Two triangles per cell, and they are the two chord qualities: the one
    // pointing up is {p, p+7, p+4}, a major triad on p; the one pointing down
    // is {p+7, p+4, p+11}, a minor triad on p+4. That is the fact the whole
    // diagram is for, and it needs no table.
    for v in 0..rows {
        for u in -1..cols {
            for (corners, fill) in [
                ([(u, v), (u + 1, v), (u, v + 1)], p.lit.gamma_multiply(0.55)),
                (
                    [(u + 1, v), (u, v + 1), (u + 1, v + 1)],
                    p.root.gamma_multiply(0.45),
                ),
            ] {
                let mask = corners
                    .iter()
                    .fold(0u16, |m, &(u, v)| m | 1 << tonnetz_pc(u, v, origin));
                if input.contains(mask) {
                    painter.add(egui::Shape::convex_polygon(
                        corners.iter().map(|&(u, v)| at(u, v)).collect(),
                        fill,
                        Stroke::NONE,
                    ));
                }
            }
        }
    }

    // The three axes as edges. Every edge is an interval: horizontal a fifth,
    // up-right a major third, up-left a minor third.
    for v in 0..=rows {
        for u in -1..=cols {
            let from = at(u, v);
            for (du, dv) in [(1, 0), (0, 1), (-1, 1)] {
                painter.line_segment([from, at(u + du, v + dv)], Stroke::new(1.0_f32, p.line));
            }
        }
    }

    for v in 0..rows {
        for u in 0..cols {
            if !l.shows(rect, u, v) {
                continue;
            }
            let c = at(u, v);
            let pc = tonnetz_pc(u, v, origin);
            let lit = has(input.pcs, pc);
            let is_root = input.root == Some(pc) || (input.root.is_none() && lit && pc == origin);
            let fill = if is_root {
                p.root
            } else if lit {
                p.lit
            } else {
                p.bg
            };
            painter.circle(
                c,
                node_r,
                fill,
                Stroke::new(1.0_f32, if lit { fill } else { p.faint }),
            );
            painter.text(
                c,
                Align2::CENTER_CENTER,
                pc_name(pc, s.prefer_flats),
                font(node_r * 0.95),
                if lit { p.lit_text } else { p.ink },
            );
        }
    }
}

// ── harmonic triangles ─────────────────────────────────────────────────────

/// Distance from the centre of the harmonic-triangle figure to a vertex.
///
/// The drawn shape is `r` to a vertex PLUS a node radius beyond it, and the
/// node radius is 0.30r, so the real extent is 1.30r and the pane has to hold
/// 2.60r. Sizing on `r` alone put the tonic node through the pane's own title.
fn hexagram_radius(rect: Rect) -> f32 {
    rect.width().min(rect.height()) * 0.5 / 1.32
}

fn draw_triangles(painter: &Painter, rect: Rect, input: Input, p: &Palette, s: &Settings) {
    let rect = title(painter, rect, "HARMONIC TRIANGLES", p);
    let c = rect.center();
    let r = hexagram_radius(rect);
    if r < 20.0 {
        return;
    }

    let tonic = input.tonic();
    // I, IV, V — the tonic, the fifth below it and the fifth above it. Written
    // as -5 and +7 rather than +5 and +7 so the arithmetic says what the
    // relationship is.
    let roots = [tonic, (tonic + 5) % 12, (tonic + 7) % 12];
    let numerals_major = ["I", "IV", "V"];
    let numerals_minor = ["i", "iv", "v"];

    // The upward triangle carries the major chords, the downward one the
    // minor. Sharing a centre makes them one shape rather than two diagrams,
    // which is the point: sliding it is a modulation.
    let up = |k: usize| {
        let a = -std::f32::consts::FRAC_PI_2 + k as f32 * std::f32::consts::TAU / 3.0;
        c + Vec2::new(a.cos(), a.sin()) * r
    };
    let down = |k: usize| {
        let a = std::f32::consts::FRAC_PI_2 + k as f32 * std::f32::consts::TAU / 3.0;
        c + Vec2::new(a.cos(), a.sin()) * r
    };

    // Vertex k of the upward triangle is I at the apex, then V and IV going
    // clockwise, so the dominant is on the right where it is usually drawn.
    let up_order = [0usize, 2, 1];
    let down_order = [0usize, 1, 2];

    let tri = |f: &dyn Fn(usize) -> Pos2| [f(0), f(1), f(2)];

    for (pts, minor) in [(tri(&up), false), (tri(&down), true)] {
        let stroke = Stroke::new(if minor { 1.0_f32 } else { 1.5 }, p.faint);
        for k in 0..3 {
            painter.line_segment([pts[k], pts[(k + 1) % 3]], stroke);
        }
    }

    let node_r = r * 0.30;
    let draw_vertex = |pos: Pos2, root: u8, minor: bool, numeral: &str| {
        let mask = if minor {
            minor_triad(root)
        } else {
            major_triad(root)
        };
        let lit = input.contains(mask);
        let fill = if lit { p.lit } else { p.bg };
        painter.circle(
            pos,
            node_r,
            fill,
            Stroke::new(
                if lit { 2.0_f32 } else { 1.0 },
                if lit { p.lit } else { p.faint },
            ),
        );
        painter.text(
            Pos2::new(pos.x, pos.y - node_r * 0.22),
            Align2::CENTER_CENTER,
            &format!(
                "{}{}",
                pc_name(root, s.prefer_flats),
                if minor { "m" } else { "" }
            ),
            font(node_r * 0.62),
            if lit { p.lit_text } else { p.ink },
        );
        painter.text(
            Pos2::new(pos.x, pos.y + node_r * 0.42),
            Align2::CENTER_CENTER,
            numeral,
            font_light(node_r * 0.44),
            if lit { p.lit_text } else { p.faint },
        );
    };

    for (k, &oi) in up_order.iter().enumerate() {
        draw_vertex(up(k), roots[oi], false, numerals_major[oi]);
    }
    for (k, &oi) in down_order.iter().enumerate() {
        draw_vertex(down(k), roots[oi], true, numerals_minor[oi]);
    }

    // The key in the middle of its own triangle.
    painter.text(
        c,
        Align2::CENTER_CENTER,
        pc_name(tonic, s.prefer_flats),
        font(r * 0.24),
        p.ink.gamma_multiply(0.55),
    );
}

/// A one-pixel seam over the top of the band, matching the fretboard's.
pub fn draw_bottom_edge(painter: &Painter, rect: Rect, s: &Settings) {
    let p = palette(s);
    painter.rect_stroke(
        Rect::from_min_max(
            Pos2::new(rect.min.x, rect.max.y - 1.0),
            Pos2::new(rect.max.x, rect.max.y),
        ),
        0.0,
        Stroke::new(1.0_f32, p.line),
        StrokeKind::Inside,
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The circle really is fifths, all the way round and back to the start.
    /// A typo in that table would still look like a circle of fifths.
    #[test]
    fn the_circle_ascends_by_fifths_and_closes() {
        for i in 0..12 {
            assert_eq!(
                FIFTHS[(i + 1) % 12],
                (FIFTHS[i] + 7) % 12,
                "position {i} is not a fifth above its neighbour"
            );
        }
        let mut seen = [false; 12];
        for pc in FIFTHS {
            assert!(!seen[pc as usize], "pitch class {pc} appears twice");
            seen[pc as usize] = true;
        }
    }

    /// Adjacent keys share six of seven notes and opposite keys share two.
    /// This is the fact the diagram exists to show, so it is worth asserting
    /// rather than trusting the drawing to make it look true.
    #[test]
    fn neighbouring_keys_are_the_closest_ones() {
        for i in 0..12usize {
            let here = major_scale(FIFTHS[i]);
            let next = major_scale(FIFTHS[(i + 1) % 12]);
            let opposite = major_scale(FIFTHS[(i + 6) % 12]);
            assert_eq!(
                (here & next).count_ones(),
                6,
                "neighbours of {i} do not share six notes"
            );
            assert_eq!(
                (here & opposite).count_ones(),
                2,
                "opposites of {i} do not share two notes"
            );
        }
    }

    /// The relative minor sits on the same spoke because it has the same key
    /// signature. Same signature means, exactly, the same seven notes.
    #[test]
    fn the_relative_minor_shares_its_majors_notes() {
        for pc in 0..12u8 {
            // A natural minor scale is its relative major's, started later.
            let rel = (pc + 9) % 12;
            let minor = major_scale(pc); // same set, different tonic
            assert_eq!(
                major_scale((rel + 3) % 12),
                minor,
                "the relative minor of {pc} does not share its notes"
            );
        }
    }

    /// Signatures run 0..6 sharps clockwise and 6..1 flats coming back.
    #[test]
    fn key_signatures_count_out_and_back() {
        let got: Vec<(u8, u8)> = (0..12).map(signature).collect();
        assert_eq!(
            got,
            vec![
                (0, 0),
                (1, 0),
                (2, 0),
                (3, 0),
                (4, 0),
                (5, 0),
                (6, 0),
                (0, 5),
                (0, 4),
                (0, 3),
                (0, 2),
                (0, 1),
            ]
        );
    }

    /// Every upward triangle in the lattice is a major triad and every
    /// downward one is a minor triad, everywhere, for any origin. This is the
    /// Tonnetz's defining property; if it fails the diagram is a decoration.
    #[test]
    fn every_tonnetz_triangle_is_a_triad() {
        for origin in 0..12u8 {
            for u in -4..4 {
                for v in -4..4 {
                    let p = tonnetz_pc(u, v, origin);
                    let up = [(u, v), (u + 1, v), (u, v + 1)]
                        .iter()
                        .fold(0u16, |m, &(u, v)| m | 1 << tonnetz_pc(u, v, origin));
                    assert_eq!(
                        up,
                        major_triad(p),
                        "the up-triangle at ({u},{v}) origin {origin} is not major on {p}"
                    );

                    let dn = [(u + 1, v), (u, v + 1), (u + 1, v + 1)]
                        .iter()
                        .fold(0u16, |m, &(u, v)| m | 1 << tonnetz_pc(u, v, origin));
                    // The minor triad shares the up-triangle's third and fifth.
                    assert_eq!(
                        dn,
                        minor_triad((p + 4) % 12),
                        "the down-triangle at ({u},{v}) origin {origin} is not minor"
                    );
                }
            }
        }
    }

    /// Neighbouring triangles share an edge, which means the two chords share
    /// two notes. That is why the Tonnetz shows voice leading at a glance.
    #[test]
    fn adjacent_triads_share_two_notes() {
        for pc in 0..12u8 {
            assert_eq!(
                (major_triad(pc) & minor_triad((pc + 4) % 12)).count_ones(),
                2
            );
            assert_eq!(
                (major_triad(pc) & minor_triad((pc + 9) % 12)).count_ones(),
                2
            );
        }
    }

    /// I, IV and V between them use every note of the major scale and no
    /// other. It is why three chords are enough for so many songs, and it
    /// keeps the triangle honest about which key it is drawing.
    #[test]
    fn one_four_and_five_spell_the_whole_key() {
        for tonic in 0..12u8 {
            let three =
                major_triad(tonic) | major_triad((tonic + 5) % 12) | major_triad((tonic + 7) % 12);
            assert_eq!(
                three,
                major_scale(tonic),
                "I-IV-V in {tonic} is not the major scale"
            );
        }
    }

    #[test]
    fn labels_parse_to_a_root_and_a_quality() {
        let cases = [
            ("C", Some((0, false))),
            ("Cm", Some((0, true))),
            ("Cmaj7", Some((0, false))),
            ("F#m7", Some((6, true))),
            ("Bb", Some((10, false))),
            ("Bbm", Some((10, true))),
            ("Ebmaj9", Some((3, false))),
            ("G7", Some((7, false))),
            ("Adim", Some((9, false))),
            ("", None),
            ("?", None),
            ("Hm", None),
        ];
        for (label, want) in cases {
            assert_eq!(parse_label(label), want, "parsing {label:?}");
        }
    }

    /// Panes are laid out in a fixed order, so turning one off never makes the
    /// other two swap places under the user's eyes.
    #[test]
    fn panes_keep_their_order_and_fill_the_band() {
        let rect = Rect::from_min_size(Pos2::ZERO, Vec2::new(900.0, 300.0));
        let all = Views {
            circle: true,
            tonnetz: true,
            triangles: true,
        };
        let got = cells(rect, all);
        assert_eq!(
            got.iter().map(|(v, _)| *v).collect::<Vec<_>>(),
            View::ALL.to_vec()
        );
        let total: f32 = got.iter().map(|(_, r)| r.width()).sum();
        assert!((total - rect.width()).abs() < 0.5, "panes left a gap");

        // Dropping the middle one keeps the outer two in the same order.
        let two = Views {
            circle: true,
            tonnetz: false,
            triangles: true,
        };
        assert_eq!(
            cells(rect, two).iter().map(|(v, _)| *v).collect::<Vec<_>>(),
            vec![View::Circle, View::Triangles]
        );
        assert!(cells(rect, Views::default()).is_empty());
    }

    /// The band takes no height when nothing is selected — the window must not
    /// grow by 300 points to show three empty panes.
    #[test]
    fn an_empty_selection_takes_no_band() {
        assert_eq!(band_height(1300.0, Views::default()), 0.0);
        assert!(
            band_height(
                1300.0,
                Views {
                    circle: true,
                    ..Default::default()
                }
            ) > 0.0
        );
    }

    /// The pane sizes the band actually produces: one, two or three diagrams
    /// across a window at every size the app offers, minus the title strip.
    fn real_panes() -> Vec<Rect> {
        let mut out = Vec::new();
        for pct in [50i64, 75, 100, 125, 150, 175, 200] {
            let w = (1300.0 * pct as f64 / 100.0).trunc() as f32;
            for n in 1..=3usize {
                let views = Views {
                    circle: true,
                    tonnetz: n >= 2,
                    triangles: n >= 3,
                };
                let h = band_height(w, views);
                let band = Rect::from_min_size(Pos2::ZERO, Vec2::new(w, h));
                for (_, cell) in cells(band, views) {
                    // What draw() hands each diagram, and then what title()
                    // leaves below itself.
                    let inner = cell.shrink(8.0);
                    let th = (inner.height() * 0.09).clamp(9.0, 15.0);
                    out.push(Rect::from_min_max(
                        Pos2::new(inner.min.x, inner.min.y + th + 2.0),
                        inner.max,
                    ));
                }
            }
        }
        out
    }

    /// Not one Tonnetz node may cross its pane. The lattice is unbounded and
    /// the pane is not; the first render put a column through the neighbouring
    /// diagram and clipped an "Eb" down to "Kb", which reads as a note name
    /// and is not one.
    #[test]
    fn no_tonnetz_node_escapes_its_pane() {
        for pane in real_panes() {
            let Some(l) = Lattice::fit(pane) else {
                continue;
            };
            for v in 0..l.rows {
                for u in 0..l.cols {
                    if !l.shows(pane, u, v) {
                        continue;
                    }
                    let node = Rect::from_center_size(l.at(u, v), Vec2::splat(l.node_r * 2.0));
                    assert!(
                        pane.contains_rect(node),
                        "node ({u},{v}) at {node:?} escapes {pane:?}"
                    );
                }
            }
        }
    }

    /// ...and the fix for that must not have emptied the diagram. A guard that
    /// hides everything also satisfies "nothing escapes", so the useful half of
    /// the property is that a real pane still shows a lattice worth looking at.
    #[test]
    fn the_tonnetz_still_has_a_lattice_left() {
        for pane in real_panes() {
            let l = Lattice::fit(pane).expect("a real pane must fit a lattice");
            let shown = (0..l.rows)
                .flat_map(|v| (0..l.cols).map(move |u| (u, v)))
                .filter(|&(u, v)| l.shows(pane, u, v))
                .count();
            assert!(
                shown >= 20,
                "only {shown} nodes survive in {pane:?} ({}x{})",
                l.cols,
                l.rows
            );
            // Every pitch class reachable, so the diagram can always light the
            // note you are playing.
            let seen: u16 = (0..l.rows)
                .flat_map(|v| (0..l.cols).map(move |u| (u, v)))
                .filter(|&(u, v)| l.shows(pane, u, v))
                .fold(0u16, |m, (u, v)| m | 1 << tonnetz_pc(u, v, 0));
            assert_eq!(seen, 0xFFF, "some pitch class has no node in {pane:?}");
        }
    }

    /// The harmonic-triangle figure, nodes included, fits the pane it is given.
    /// It did not: the tonic node was drawn over the pane's own title.
    #[test]
    fn the_hexagram_fits_under_its_own_title() {
        for pane in real_panes() {
            let r = hexagram_radius(pane);
            let extent = r * 1.30 * 2.0;
            assert!(
                extent <= pane.width().min(pane.height()) + 0.5,
                "the figure is {extent} across in a {:?} pane",
                pane.size()
            );
        }
    }

    /// Every character the band draws must reach the screen. The key
    /// signatures were written with U+266F and U+266D, which neither bundled
    /// face nor the fallback chain has, so they drew as tofu boxes — and a
    /// missing accidental turns "2 sharps" into "2 something".
    #[test]
    fn every_glyph_the_band_draws_exists() {
        // EVERY bundled face, not just the default: the typeface is a user
        // choice, so a glyph missing from one of them is a glyph missing for
        // whoever picked it.
        let bundled: &[(&str, &[u8])] = &[
            ("Courier Prime", fonts::COURIER_PRIME_REGULAR),
            ("Courier Prime Bold", fonts::COURIER_PRIME_BOLD),
            ("Terminess", fonts::TERMINESS_REGULAR),
            ("Terminess Bold", fonts::TERMINESS_BOLD),
            ("JetBrains Mono", fonts::JETBRAINS_REGULAR),
            ("JetBrains Mono Bold", fonts::JETBRAINS_BOLD),
        ];
        let mut drawn: Vec<char> = Vec::new();
        for pc in 0..12u8 {
            drawn.extend(pc_name(pc, true).chars());
            drawn.extend(pc_name(pc, false).chars());
            drawn.extend(pc_name(pc, true).to_lowercase().chars());
        }
        for i in 0..12usize {
            let (sharps, flats) = signature(i);
            drawn.extend(format!("{sharps}#{flats}b").chars());
        }
        drawn.extend("CIRCLE OF FIFTHS TONNETZ HARMONIC TRIANGLES".chars());
        drawn.extend("I IV V i iv v no key fits keys 0123456789".chars());
        drawn.sort_unstable();
        drawn.dedup();

        for c in drawn {
            for (name, bytes) in bundled {
                assert!(
                    ttf_parser::Face::parse(bytes, 0)
                        .map(|f| f.glyph_index(c).is_some())
                        .unwrap_or(false),
                    "{name} has no glyph for {c:?} (U+{:04X})",
                    c as u32
                );
            }
        }
    }

    /// Every pane must draw without panicking at any size the layout can hand
    /// it, holding anything from nothing to all twelve notes. These are
    /// painters full of trigonometry and integer row counts; a zero-width band
    /// or a degenerate lattice is exactly where that breaks.
    #[test]
    fn every_pane_draws_at_every_size() {
        let ctx = egui::Context::default();
        // Every label here is a real glyph, and a bare Context has no font
        // families bound, so painting one panics rather than failing.
        fonts::install(&ctx, fonts::FontChoice::default(), None);
        let s = Settings::default();
        for w in [40.0_f32, 120.0, 400.0, 1300.0, 2600.0] {
            for views in [
                Views {
                    circle: true,
                    ..Default::default()
                },
                Views {
                    tonnetz: true,
                    ..Default::default()
                },
                Views {
                    triangles: true,
                    ..Default::default()
                },
                Views {
                    circle: true,
                    tonnetz: true,
                    triangles: true,
                },
            ] {
                let h = band_height(w, views);
                let rect = Rect::from_min_size(Pos2::ZERO, Vec2::new(w, h));
                for pcs in [0u16, 0b0000_1001_0001, 0xFFF, 0b1000_0000_0001] {
                    let input = Input {
                        pcs,
                        bass: (pcs != 0).then_some(0),
                        root: (pcs != 0).then_some(0),
                        minor: false,
                    };
                    let _ = ctx.run(Default::default(), |ctx| {
                        let painter = ctx.layer_painter(egui::LayerId::background());
                        draw(&painter, rect, views, input, &s);
                    });
                }
            }
        }
    }
}
