#!/usr/bin/env bash
# Generate THIRD-PARTY-LICENSES at the repo root from cargo metadata.
#
#   scripts/gen-third-party-licenses.sh
#
# Uses cargo-license if installed (`cargo install cargo-license`), otherwise
# falls back to `cargo metadata` + python3. Rerun after any dependency change;
# the build scripts bundle the output into every release artifact.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Homebrew rust shadows rustup's cargo on PATH; prefer the rustup toolchain.
TOOLCHAIN_BIN="$(rustup which cargo 2>/dev/null | xargs dirname || true)"
[ -n "$TOOLCHAIN_BIN" ] && export PATH="$TOOLCHAIN_BIN:$HOME/.cargo/bin:$PATH"

OUT="THIRD-PARTY-LICENSES"

cat > "$OUT" <<'EOF'
THIRD-PARTY LICENSES — Tangent
============================

Fonts
-----
Tangent's executable statically embeds SIX font files. All six are free/libre,
none is modified or subset, and none is ever sold standalone. Tangent does not
bundle or redistribute Courier New. The full license text for every font ships
in every Tangent distribution, at the paths given below.

  Courier Prime Regular + Bold  --  Tangent's UI typeface
      Copyright 2015 The Courier Prime Project Authors
      (https://github.com/quoteunquoteapps/CourierPrime)
      SIL Open Font License 1.1  ->  OFL.txt

  Terminess Nerd Font Mono Regular + Bold  --  optional UI typeface
      Copyright (C) 2020 Dimitar Toshkov Zhekov
      Copyright (C) 2023 Tilman Blumenbach
      SIL Open Font License 1.1  ->  font-licenses/Terminess-OFL-1.1.txt

The remaining four arrive with eframe/egui's `default_fonts` feature (crate
epaint_default_fonts 0.35.0) and act as glyph fallback. Their license texts
ship in the font-licenses/ folder of every artifact:

  Ubuntu Light
      Copyright 2011 Canonical Ltd.
      Ubuntu Font Licence 1.0  ->  font-licenses/Ubuntu-Font-Licence-1.0.txt

  Noto Emoji Regular
      Copyright 2013 Google Inc. All Rights Reserved.
      SIL Open Font License 1.1  ->  font-licenses/NotoEmoji-OFL-1.1.txt

  Hack Regular
      Copyright (c) 2018 Source Foundry Authors  --  MIT License
      Copyright (c) 2003 Bitstream, Inc.  --  Bitstream Vera License
      ->  font-licenses/Hack-LICENSE.txt

  emoji-icon-font
      Copyright (c) 2014 John Slegers  --  MIT License
      ->  font-licenses/emoji-icon-font-MIT.txt

Tangent's own MIT grant (LICENSE) covers Tangent's source and compiled code only.
The fonts above are not relicensed by it and remain under their own terms.

Rust crates
-----------
The Rust crates statically linked into Tangent are listed below with their
declared licenses and authors, as resolved from Cargo.lock (all platforms).
Generated by scripts/gen-third-party-licenses.sh — regenerate after any
dependency change.

EOF

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if command -v cargo-license >/dev/null 2>&1; then
  cargo license --json > "$TMP/licenses.json"
  python3 - "$TMP/licenses.json" >> "$OUT" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    rows = json.load(f)
skip = {"ivory", "ivory-core", "ivory-ui"}
rows = sorted((r for r in rows if r["name"] not in skip),
              key=lambda r: (r["name"].lower(), r["version"]))
for r in rows:
    print(f'{r["name"]} {r["version"]}')
    print(f'    license: {r.get("license") or "unknown"}')
    print(f'    authors: {r.get("authors") or "unknown"}')
    if r.get("repository"):
        print(f'    repository: {r["repository"]}')
    print()
print(f"({len(rows)} crates)")
PY
else
  cargo metadata --format-version 1 --locked > "$TMP/metadata.json"
  python3 - "$TMP/metadata.json" >> "$OUT" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    meta = json.load(f)
ws = set(meta.get("workspace_members", []))
pkgs = sorted((p for p in meta["packages"] if p["id"] not in ws),
              key=lambda p: (p["name"].lower(), p["version"]))
for p in pkgs:
    lic = p.get("license") or (
        f'see {p["license_file"]}' if p.get("license_file") else "unknown")
    authors = ", ".join(p.get("authors") or []) or "unknown"
    print(f'{p["name"]} {p["version"]}')
    print(f'    license: {lic}')
    print(f'    authors: {authors}')
    if p.get("repository"):
        print(f'    repository: {p["repository"]}')
    print()
print(f"({len(pkgs)} crates)")
PY
fi

echo "==> $OUT ($(grep -c 'license:' "$OUT") crates listed)"
