#!/usr/bin/env bash
# Generate THIRD-PARTY-LICENSES at the repo root from cargo metadata.
#
#   scripts/gen-third-party-licenses.sh
#
# Uses cargo-license if installed (`cargo install cargo-license`), otherwise
# falls back to `cargo metadata` + python3. Rerun after any dependency change;
# the build scripts bundle the output into every release artifact.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Homebrew rust shadows rustup's cargo on PATH; prefer the rustup toolchain.
TOOLCHAIN_BIN="$(rustup which cargo 2>/dev/null | xargs dirname || true)"
[ -n "$TOOLCHAIN_BIN" ] && export PATH="$TOOLCHAIN_BIN:$HOME/.cargo/bin:$PATH"

OUT="THIRD-PARTY-LICENSES"

cat > "$OUT" <<'EOF'
THIRD-PARTY LICENSES — Ivory
============================

Fonts
-----
Ivory bundles the Courier Prime fonts, Copyright 2015 The Courier Prime
Project Authors (https://github.com/quoteunquoteapps/CourierPrime), licensed
under the SIL Open Font License, Version 1.1. The full license text ships
alongside the fonts as OFL.txt in every Ivory distribution. The fonts are not
sold standalone. Ivory does not redistribute Courier New.

Rust crates
-----------
The Rust crates statically linked into Ivory are listed below with their
declared licenses and authors, as resolved from Cargo.lock (all platforms).
Generated by scripts/gen-third-party-licenses.sh — regenerate after any
dependency change.

EOF

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if command -v cargo-license >/dev/null 2>&1; then
  cargo license --json > "$TMP/licenses.json"
  python3 - "$TMP/licenses.json" >> "$OUT" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    rows = json.load(f)
skip = {"ivory", "ivory-core"}
rows = sorted((r for r in rows if r["name"] not in skip),
              key=lambda r: (r["name"].lower(), r["version"]))
for r in rows:
    print(f'{r["name"]} {r["version"]}')
    print(f'    license: {r.get("license") or "unknown"}')
    print(f'    authors: {r.get("authors") or "unknown"}')
    if r.get("repository"):
        print(f'    repository: {r["repository"]}')
    print()
print(f"({len(rows)} crates)")
PY
else
  cargo metadata --format-version 1 --locked > "$TMP/metadata.json"
  python3 - "$TMP/metadata.json" >> "$OUT" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    meta = json.load(f)
ws = set(meta.get("workspace_members", []))
pkgs = sorted((p for p in meta["packages"] if p["id"] not in ws),
              key=lambda p: (p["name"].lower(), p["version"]))
for p in pkgs:
    lic = p.get("license") or (
        f'see {p["license_file"]}' if p.get("license_file") else "unknown")
    authors = ", ".join(p.get("authors") or []) or "unknown"
    print(f'{p["name"]} {p["version"]}')
    print(f'    license: {lic}')
    print(f'    authors: {authors}')
    if p.get("repository"):
        print(f'    repository: {p["repository"]}')
    print()
print(f"({len(pkgs)} crates)")
PY
fi

echo "==> $OUT ($(grep -c 'license:' "$OUT") crates listed)"
