//! Embed the Windows icon and version block into `tangent.exe`.
//!
//! This used to be four lines of `winres` behind `#[cfg(windows)]`, and it
//! never ran once. Both of those gates are evaluated for the HOST, not the
//! target: `[target.'cfg(windows)'.build-dependencies]` means "when building
//! ON Windows", and a `#[cfg(windows)]` inside a build script means the same.
//! Every Windows release Tangent has ever shipped was cross-compiled from
//! macOS, so the resource compiler was never even a dependency, and the
//! shipped `.exe` has no `.rsrc` section at all — no icon in Explorer, no
//! icon on the taskbar, and blank Properties. The failure was silent in both
//! directions: nothing to see in the build log, and nothing missing on the
//! machine doing the building.
//!
//! So this reads `CARGO_CFG_TARGET_OS` — the TARGET, which is the thing that
//! actually decides whether a resource makes sense — writes an `.rc`, compiles
//! it with whichever resource compiler is around, and hands the result to the
//! linker. `lld-link` (what cargo-xwin uses) and `link.exe` both take a `.res`
//! as a plain input file.
//!
//! It is best-effort by design. A missing resource compiler must not stop a
//! Windows build; it produces the same binary as before, minus the icon. But
//! it now says so.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../assets/ivory.ico");

    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".into());
    // "2.3.0" -> "2,3,0,0", which is the only form FILEVERSION accepts.
    let mut parts: Vec<String> = version
        .split(|c: char| !c.is_ascii_digit())
        .filter(|s| !s.is_empty())
        .take(4)
        .map(|s| s.to_owned())
        .collect();
    while parts.len() < 4 {
        parts.push("0".into());
    }
    let quad = parts.join(",");

    // The icon is generated by scripts/build-cross.sh before cargo runs, so in
    // a plain `cargo build` it may not be there. Version info is still worth
    // embedding on its own — it is what Properties -> Details reads.
    let icon = Path::new("../assets/ivory.ico").canonicalize().ok();
    let icon_line = match &icon {
        // Forward slashes: llvm-rc and windres both accept them, and a
        // backslash in an .rc string is an escape character.
        Some(p) => format!(
            "1 ICON \"{}\"\n",
            p.display().to_string().replace('\\', "/")
        ),
        None => {
            println!("cargo:warning=assets/ivory.ico is missing; tangent.exe will have no icon");
            String::new()
        }
    };

    let rc = format!(
        r#"{icon_line}
1 VERSIONINFO
FILEVERSION {quad}
PRODUCTVERSION {quad}
FILEOS 0x40004L
FILETYPE 0x1L
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK "040904b0"
    BEGIN
      VALUE "CompanyName", "ganten"
      VALUE "FileDescription", "Tangent - what you are playing, named"
      VALUE "FileVersion", "{version}"
      VALUE "InternalName", "tangent"
      VALUE "LegalCopyright", "MIT"
      VALUE "OriginalFilename", "tangent.exe"
      VALUE "ProductName", "Tangent"
      VALUE "ProductVersion", "{version}"
    END
  END
  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", 0x409, 1200
  END
END
"#
    );

    let rc_path = out.join("tangent.rc");
    let res_path = out.join("tangent.res");
    if fs::write(&rc_path, rc).is_err() {
        println!("cargo:warning=could not write {}", rc_path.display());
        return;
    }

    // Whatever is available. `llvm-rc` ships with LLVM (Homebrew's llvm, which
    // cargo-xwin already needs); `rc.exe` is the Windows SDK's; `windres` is
    // mingw's and takes different flags.
    //
    // Resolved to an ABSOLUTE path rather than left to PATH lookup. Homebrew's
    // llvm is keg-only, so `llvm-rc` is not on PATH even on a machine that has
    // it and is using its clang to cross-compile — and setting `PATH` in the
    // child's environment does not affect how the program name itself is
    // looked up, which is the shape this bug took the first time.
    let llvm_rc = env::var("LLVM_RC").ok().unwrap_or_else(|| {
        [
            "/opt/homebrew/opt/llvm/bin/llvm-rc",
            "/usr/local/opt/llvm/bin/llvm-rc",
        ]
        .into_iter()
        .find(|p| Path::new(p).exists())
        .unwrap_or("llvm-rc")
        .to_owned()
    });
    // BARE FILENAMES, run from OUT_DIR. `llvm-rc` and `rc.exe` follow the
    // Windows convention that an argument beginning with `/` is a SWITCH, so
    // an absolute Unix input path is not an input at all: `/Users/...` is read
    // as the `/U` option with a long tail, and the tool then reports
    //
    //     Exactly one input file should be provided.
    //
    // while pointing at nothing. It is a genuinely confusing message, and it
    // depends on the first letter of the path — `/private/tmp/...` happens to
    // work, `/Users/...` does not, so this reproduces on a real build and not
    // in a scratch directory.
    let attempts: [(&str, Vec<String>); 3] = [
        (
            llvm_rc.as_str(),
            vec!["/fotangent.res".into(), "tangent.rc".into()],
        ),
        (
            "rc.exe",
            vec!["/fo".into(), "tangent.res".into(), "tangent.rc".into()],
        ),
        (
            "x86_64-w64-mingw32-windres",
            vec![
                "tangent.rc".into(),
                "-O".into(),
                "coff".into(),
                "-o".into(),
                "tangent.res".into(),
            ],
        ),
    ];

    for (tool, args) in attempts {
        match Command::new(tool).args(&args).current_dir(&out).status() {
            Ok(st) if st.success() && res_path.exists() => {
                // Both link.exe and lld-link accept a .res as an input file.
                println!("cargo:rustc-link-arg-bins={}", res_path.display());
                return;
            }
            // A tool that is absent is the ordinary case (only one of these
            // three exists on any given machine); a tool that is present and
            // FAILS is worth saying out loud.
            Ok(st) => {
                println!("cargo:warning={tool} exited {st}");
                continue;
            }
            Err(_) => continue,
        }
    }

    println!(
        "cargo:warning=no resource compiler found (tried llvm-rc, rc.exe, windres); \
         tangent.exe will have no icon or version info. \
         On macOS: brew install llvm"
    );
}
